# Generated by Django 4.1.6 on 2023-02-26 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=255)),
                ('grouptotal', models.FloatField()),
                ('groupmonthly', models.FloatField()),
                ('groupcount', models.IntegerField()),
                ('groupstatus', models.CharField(max_length=50)),
                ('groupvisibilty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=255)),
                ('memberphone', models.CharField(max_length=50)),
                ('memberid', models.CharField(max_length=50)),
                ('memberstatus', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Required',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiredrule', models.CharField(max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islamApp.members')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rulename', models.CharField(max_length=50)),
                ('booked', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islamApp.groups')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouprule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islamApp.grouprules')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='islamApp.members')),
            ],
        ),
    ]
