# Generated by Django 4.1.6 on 2023-02-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('islamApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='DGroups',
        ),
    ]
