# Generated by Django 4.1.6 on 2023-02-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islamApp', '0002_rename_groups_dgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='required',
            name='requirementstatus',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
