# Generated by Django 4.1.6 on 2023-02-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islamApp', '0003_required_requirementstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='required',
            name='requirementstatus',
            field=models.CharField(max_length=50),
        ),
    ]
